name: Build

on: [push]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest - MSVC", os: windows-latest,
            artifact: "partitioner.exe", artifact_path: "Release/partitioner.exe",
            cxx: "cl",
          }
        - {
            name: "Ubuntu Latest - GCC", os: ubuntu-latest,
            artifact: "partitioner", artifact_path: "partitioner",
            cxx: "g++-10"
          }

    steps:
      - uses: actions/checkout@v2
      - name: Set Windows environment
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
      - name: CMake configure
        run: cmake  -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}
      - name: CMake build
        run: cmake --build build --config Release
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./build/${{ matrix.config.artifact_path }}
          name: ${{ matrix.config.artifact }}
